### ISSUE TITLE
Negative values won't come in view

### ISSUE THREAD

**Issue by basdvries** [nhatminh12369/LineChart#2]
Negative values will always be plotted outside of the graph.

**Comment by nhatminh12369** [comment]
Hi, thanks for letting me know, I was quite busy in the last two weeks to reply to you.

I have submitted a fix to this issue.

However, please bear in mind that this is just a sample source code created as part of a tutorial on Medium. You should not import it directly into your project. What I recommend is that you can take the idea from the tutorial if you think that it is useful and implement the chart view yourself.

Thanks.
